version: "3"

services:
  postgres:
    image: postgres:14.3
    container_name: postgres_clean_template
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
